services:
  ord-indexer:
    image: junkcoin/ord-junkcoin-prod
    env_file:
      - .env
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - STARTING_SATS_PATH=/starting_sats.json
      - SUBSIDIES_PATH=/subsidies.json
      - FIRST_INSCRIPTION_HEIGHT=273000
      - FIRST_JUNE_HEIGHT=300000
    tty: false
    restart: "always"
    # for the indexer to be able to connect to the local junkcoin node we use the host network
    network_mode: "host"
    #    ports:
    #      - ${ORD_HTTP_PORT:-8080}:80
    entrypoint: [
      "ord",
      "--rpc-url=${RPC_URL}",
      "--data-dir=/root/.data",
      "--nr-parallel-requests=10",
      "--first-inscription-height=${FIRST_INSCRIPTION_HEIGHT}",
      "--first-june-height=${FIRST_JUNE_HEIGHT}",
      "--index-junes",
      "--index-transactions",
      "--index-junk20",
      "server"
    ]
    volumes:
      - ${DOG_MOUNT_DIR_INDEXER:-/mnt/ord-node}/indexer-data-main:/root/.data:delegated
      # If your junkcoin node is running in a container, you can mount the junkcoin data directory to the indexer container
      # - dog-data:/root/.junkcoin
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    privileged: true
